vim.cmd("set mouse+=a")
vim.opt.relativenumber = true
vim.opt.number = true
vim.opt.cursorline = true
vim.g.netrw_banner = 0
vim.opt.timeoutlen = 200
vim.opt.expandtab = true
vim.opt.smartindent = true
vim.opt.tabstop = 2
vim.opt.shiftwidth = 2
