#!/usr/bin/env bash
file=$1
w=`expr $2 - 3`
h=$3
x=`expr $4 + 1`
y=$5

filetype="$( file -Lb --mime-type "$file")"

if [[ "$filetype" =~ ^image ]]; then
    kitty +icat --silent --transfer-mode file --place "${w}x${h}@${x}x${y}" "$file"
    exit 1
fi

if [[ "$filetype" == text/* ]] || [[ "$filetype" == *json* ]]; then
  cat "$1"
  exit 1
fi

echo $filetype
exit 1
