filetype plugin indent on
syntax on
set expandtab tabstop=2 softtabstop=2 shiftwidth=2
set nocompatible number autoindent smartindent cursorline showcmd wildmenu autoread nobackup
set clipboard+=unnamed
set completeopt=menuone,longest,noinsert
set shortmess+=c
set omnifunc=ccomplete#Complete
set statusline=\ %f%m\ %=\ %p%%\ 
highlight CursorLine term=none cterm=none
highlight CursorLineNr term=none cterm=none
highlight LineNr ctermfg=darkgray term=none cterm=none
highlight Visual term=standout cterm=standout
highlight VisualNOS term=standout cterm=standout
" better window split style
set fillchars+=vert:\▏,eob:\ 
highlight VertSplit cterm=NONE
let &t_SI = "\<Esc>[6 q" " set cursor to a vertical bar in insert mode
let &t_EI = "\<Esc>[2 q" " set cursor to a block in normal mode
if !has('gui_running')
	set t_Co=256
endif
" Ctrl S to save
nnoremap <C-s> :w<CR>
nnoremap <C-S-s> :wa<CR>
nnoremap <C-f> /
" nice try, Ex mode
nnoremap Q <Nop>
nnoremap q: :
" delete single character without copying into register
nnoremap x "_x
nnoremap <Esc> :noh<CR>
" Navigate buffers
nnoremap <Tab> :b#<CR>
nnoremap <Space>b :buffers<CR>:b<Space>
" Navigate windows
nnoremap <C-j> <C-W>j
nnoremap <C-k> <C-W>k
nnoremap <C-h> <C-W>h
nnoremap <C-l> <C-W>l
" FZF
nnoremap <Space>f :FZF<CR>
nnoremap <C-S-f> :Ag<CR>
nnoremap <Space><Space> :Ag<CR>
" autocomplete
let g:mucomplete#enable_auto_at_startup = 1
