filetype plugin indent on
syntax on
set expandtab tabstop=2 softtabstop=2 shiftwidth=2
set nocompatible number autoindent smartindent cursorline showcmd wildmenu autoread nobackup
set background=dark
set clipboard+=unnamed
set completeopt=menuone,longest
set shortmess+=c
set omnifunc=ccomplete#Complete
highlight EndOfBuffer ctermfg=16
highlight CursorLine ctermbg=16 term=none cterm=none
highlight CursorLineNr term=none cterm=none
highlight LineNr ctermfg=black term=none cterm=none
" better window split style
set fillchars+=vert:\▏
highlight VertSplit cterm=NONE
let &t_SI = "\<Esc>[6 q" " set cursor to a vertical bar in insert mode
let &t_EI = "\<Esc>[2 q" " set cursor to a block in normal mode
if !has('gui_running')
	set t_Co=256
endif
" Navigate buffers
nnoremap <Tab> :b#<CR>
nnoremap <Space>b :buffers<CR>:b<Space>
" Navigate windows
map <C-j> <C-W>j
map <C-k> <C-W>k
map <C-h> <C-W>h
map <C-l> <C-W>l
" FZF
nnoremap <Space>f :FZF<CR>
nnoremap <Space><Space> :Ag<CR>
" nice try, Ex mode
map Q <Nop>
map q: :
" delete single character without copying into register
nnoremap x "_x
nnoremap <Esc> :noh<CR>
" vim-airline + vim-airline-themes is required
let g:airline_symbols_ascii = 1
let g:airline_theme='papercolor'
