#!/usr/bin/env bash

## Copyright (C) 2020-2021 Aditya Shakya <adi1090x@gmail.com>
## Everyone is permitted to copy and distribute copies of this file under GNU-GPL3
SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
rofi \
	-show drun \
	-scroll-method 0 \
	-drun-match-fields all \
	-drun-display-format "{name}" \
	-kb-cancel Escape,Alt+F1 \
	-theme "$SCRIPT_DIR/launcher.rasi"
