#!/usr/bin/env bash

## Copyright (C) 2020-2021 Aditya Shakya <adi1090x@gmail.com>
## Everyone is permitted to copy and distribute copies of this file under GNU-GPL3

## Environtment
export PATH="${PATH}:$HOME/.config/bspwm/bin"

## Configurations --------------------------------------------#
workspaces() {
	name=1
	for monitor in `bspc query -M`; do
		#bspc monitor ${monitor} -n "$name" -d 'I' 'II' 'III' 'IV' 'V' 'VI' 'VII' 'VIII'
		#bspc monitor ${monitor} -n "$name" -d '' '' '' '' '' '' '' ''
		bspc monitor ${monitor} -n "$name" -d 'ﲵ' '' '﬏' '' ''
		let name++
	done
}
workspaces

bspc config border_width 1
bspc config window_gap 5
bspc config split_ratio 0.50

bspc config focused_border_color "#81A1C1" 
bspc config normal_border_color "#2E3440"
bspc config active_border_color "#B48EAD"
bspc config presel_feedback_color "#A3BE8C"

bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config paddingless_monocle true
bspc config single_monocle false
#bspc config focus_follows_pointer true

## Window rules ----------------------------------------------#

# remove all rules first
bspc rule -r *:*

# 1 > terminal
declare -a term=(Alacritty kitty)
for i in ${term[@]}; do
  bspc rule -a $i desktop='^1' follow=on focus=on
done

# 2 > web
declare -a browser=(Chromium Google-chrome)
for i in ${browser[@]}; do
  bspc rule -a $i desktop='^2' follow=on focus=on
done

# 3 > code
declare -a code=(code-oss code)
for i in ${code[@]}; do
   bspc rule -a $i desktop='^3' follow=on focus=on;
done

# 5 > unreal
declare -a unreal=(UnrealEditor UE4Editor)
for i in ${unreal[@]}; do
   bspc rule -a $i desktop='^5' state=floating follow=on focus=on manage=off;
done

# special rules
declare -a floating=(Steam Yad 'Firefox:Places' Viewnior kooha)
for i in ${floating[@]}; do
   bspc rule -a $i state=floating follow=on focus=on;
done

bspfloat &
bspfocus &
## Autostart -------------------------------------------------#

# Kill if already running
killall -9 picom polybar eww sxhkd dunst ksuperkey mpd

# Lauch keybindings daemon
sxhkd &

# Enable Super Keys For Menu
ksuperkey -e 'Super_L=Alt_L|F1' &
ksuperkey -e 'Super_R=Alt_L|F1' &

# picom --experimental-backends &
# Fix cursor
xsetroot -cursor_name left_ptr

# Restore wallpaper
nitrogen --restore

# Start mpd
exec mpd &

eww daemon
eww open bar
# Start bspwm scripts
## Launch dunst daemon
dunst &
